/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreaAreaIdRouteImport } from './routes/area.$areaId'
import { Route as AreaAreaIdNoteIdRouteImport } from './routes/area.$areaId.$noteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaAreaIdRoute = AreaAreaIdRouteImport.update({
  id: '/area/$areaId',
  path: '/area/$areaId',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaAreaIdNoteIdRoute = AreaAreaIdNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => AreaAreaIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/area/$areaId': typeof AreaAreaIdRouteWithChildren
  '/area/$areaId/$noteId': typeof AreaAreaIdNoteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/area/$areaId': typeof AreaAreaIdRouteWithChildren
  '/area/$areaId/$noteId': typeof AreaAreaIdNoteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/area/$areaId': typeof AreaAreaIdRouteWithChildren
  '/area/$areaId/$noteId': typeof AreaAreaIdNoteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/area/$areaId' | '/area/$areaId/$noteId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/area/$areaId' | '/area/$areaId/$noteId'
  id: '__root__' | '/' | '/area/$areaId' | '/area/$areaId/$noteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreaAreaIdRoute: typeof AreaAreaIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area/$areaId': {
      id: '/area/$areaId'
      path: '/area/$areaId'
      fullPath: '/area/$areaId'
      preLoaderRoute: typeof AreaAreaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area/$areaId/$noteId': {
      id: '/area/$areaId/$noteId'
      path: '/$noteId'
      fullPath: '/area/$areaId/$noteId'
      preLoaderRoute: typeof AreaAreaIdNoteIdRouteImport
      parentRoute: typeof AreaAreaIdRoute
    }
  }
}

interface AreaAreaIdRouteChildren {
  AreaAreaIdNoteIdRoute: typeof AreaAreaIdNoteIdRoute
}

const AreaAreaIdRouteChildren: AreaAreaIdRouteChildren = {
  AreaAreaIdNoteIdRoute: AreaAreaIdNoteIdRoute,
}

const AreaAreaIdRouteWithChildren = AreaAreaIdRoute._addFileChildren(
  AreaAreaIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreaAreaIdRoute: AreaAreaIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
